
--------------------------- 테입블 drop 순서 (start-over할때)
DROP TABLE "AUTHOR";
DROP TABLE "BOARD_IMG";
DROP TABLE "CHAT_MEMBER";
DROP TABLE "CHATTING_MESSAGE";
DROP TABLE "CHATTING_ROOM";
DROP TABLE "COMMENT";
DROP TABLE "CONTRIBUTOR";
DROP TABLE "EXHIBITION";
DROP TABLE "INSTITUTION";
DROP TABLE "LIKE";
DROP TABLE "NOTIFICATION";
DROP TABLE "PAY_BACK";
DROP TABLE "PM_PIRCE_LIST"; -- 이전 버전
DROP TABLE "PM_PRICE_LIST"; -- 현재 버전
DROP TABLE "STAR";
DROP TABLE "BANK_INFO";
DROP TABLE "PAY";
DROP TABLE "PM";
DROP TABLE "PM_HOUSE";
DROP TABLE "BOARD";
DROP TABLE "BOARDTYPE";
DROP TABLE "GENRE";
DROP TABLE "MEMBER";
DROP TABLE "QUESTION";

---------------------------------
DROP SEQUENCE "SEQ_AUTHOR_NO";


DROP TABLE "AUTHOR";

CREATE TABLE "AUTHOR" (
   "AUTHOR_NO"   NUMBER      NOT NULL,
   "AUTHOR_NAME"   VARCHAR2(500 CHAR)      NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "AUTHOR"."AUTHOR_NO" IS '전시작가번호(SEQ_AUTHOR_NO)';

COMMENT ON COLUMN "AUTHOR"."AUTHOR_NAME" IS '전시작가이름';

COMMENT ON COLUMN "AUTHOR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_ID"   VARCHAR2(20)      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(30)      NOT NULL,
   "MEMBER_PW"   VARCHAR2(30)      NOT NULL,
   "MEMBER_NICKNAME"   VARCHAR2(30)      NOT NULL,
   "MEMBER_TEL"   VARCHAR2(12)      NOT NULL,
   "MEMBER_ADDR"   VARCHAR2(150)      NULL,
   "MEMBER_ADMIN"   CHAR(1)      NOT NULL,
   "PROFILE_IMG"   VARCHAR2(300)      NULL,
   "MEMBER_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADMIN" IS '관리자 로그인 여부(일반: N, 관리자: Y)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부(일반: N 탈퇴: Y)';

DROP TABLE "PM";

CREATE TABLE "PM" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "GENRE_NO"   NUMBER      NOT NULL,
   "PM_START_TIME"   DATE      NOT NULL,
   "PM_END_TIME"   DATE      NOT NULL,
   "PM_PLAYTIME"   VARCHAR2(500)      NOT NULL,
   "PM_HOUSE_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PM"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PM"."GENRE_NO" IS 'SEQ_GENRE_NO';

COMMENT ON COLUMN "PM"."PM_START_TIME" IS '공연 시작일';

COMMENT ON COLUMN "PM"."PM_END_TIME" IS '공연 종료일';

COMMENT ON COLUMN "PM"."PM_PLAYTIME" IS '상영 시간';

COMMENT ON COLUMN "PM"."PM_HOUSE_NO" IS '공연 시설 번호';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "BOARD_TITLE"   VARCHAR2(300 CHAR)      NOT NULL,
   "BOARD_CONTENT"   VARCHAR2(4000 CHAR)      NULL,
   "B_CREATE_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "B_UPDATE_DATE"   DATE      NULL,
   "BOARD_COUNT"   NUMBER   DEFAULT 0   NOT NULL,
   "BOARD_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "MEMBER_NO"   NUMBER      NULL,
   "COMMUNITY_CODE"   NUMBER      NOT NULL,
   "Q_CODE"   NUMBER   DEFAULT 1   NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."B_CREATE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."B_UPDATE_DATE" IS '게시글 최종 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_COUNT" IS '게시글 조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."Q_CODE" IS '문의 번호(티켓: 1, 커뮤니티: 2, 회원/공통/기타: 3)';

DROP TABLE "PAY_BACK";

CREATE TABLE "PAY_BACK" (
   "PORTONE_NO"   VARCHAR2(100)      NOT NULL,
   "REFUND_HOLDER"   VARCHAR2(10)      NOT NULL,
   "REFUND_ACCOUNT"   NUMBER      NOT NULL,
   "REFUND_BANK"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PAY_BACK"."PORTONE_NO" IS '포트원에서 발급하는 고유 번호';

COMMENT ON COLUMN "PAY_BACK"."REFUND_HOLDER" IS '환불 수령계좌 예금주';

COMMENT ON COLUMN "PAY_BACK"."REFUND_ACCOUNT" IS '환불 수령계좌 번호';

COMMENT ON COLUMN "PAY_BACK"."REFUND_BANK" IS '은행 코드';

DROP TABLE "PM_HOUSE";

CREATE TABLE "PM_HOUSE" (
   "PM_HOUSE_NO"   NUMBER      NOT NULL,
   "PM_HOUSE_NAME"   VARCHAR2(200)      NOT NULL,
   "PM_HOUSE_ADDRESS"   VARCHAR2(500)      NOT NULL,
   "PM_HOUSE_LAT"   BINARY_DOUBLE      NOT NULL,
   "PM_HOUSE_LONG"   BINARY_DOUBLE      NOT NULL,
   "PM_HOUSE_WEBSITE"   VARCHAR2(300)      NOT NULL,
   "PM_HOUSE_HOME"   VARCHAR2(50)      NOT NULL
);

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_NO" IS 'SEQ_HOUSE_NO';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_NAME" IS '시설 이름';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_ADDRESS" IS '시설 주소';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_LAT" IS '시설 위도';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_LONG" IS '시설 경도';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_WEBSITE" IS '시설 홈페이지';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_HOME" IS '시설 전화번호';

DROP TABLE "CONTRIBUTOR";

CREATE TABLE "CONTRIBUTOR" (
   "CONTRIBUTOR_NO"   NUMBER      NOT NULL,
   "EXHIBIT_HOST"   VARCHAR2(200 CHAR)      NULL,
   "EXHIBIT_SUPPORT"   VARCHAR2(200 CHAR)      NULL,
   "BOARD_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CONTRIBUTOR"."CONTRIBUTOR_NO" IS '전시주최후원번호(SEQ_CONTRIBUTOR_NO)';

COMMENT ON COLUMN "CONTRIBUTOR"."EXHIBIT_HOST" IS '전시주최';

COMMENT ON COLUMN "CONTRIBUTOR"."EXHIBIT_SUPPORT" IS '전시후원';

COMMENT ON COLUMN "CONTRIBUTOR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "INSTITUTION";

CREATE TABLE "INSTITUTION" (
   "INSTITUTION_NO"   NUMBER      NOT NULL,
   "EXHIBIT_INST_NAME"   VARCHAR(200 CHAR)      NOT NULL,
   "EXHIBIT_INST_TEL"   VARCHAR2(50 CHAR)      NOT NULL,
   "EXHIBIT_LOCATION"   VARCHAR2(100 CHAR)      NULL
);

COMMENT ON COLUMN "INSTITUTION"."INSTITUTION_NO" IS '전시기관번호(SEQ_INSTITUTION_NO)';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_INST_NAME" IS '전시기관이름';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_INST_TEL" IS '전시기관문의대표전화번호(DEFAULT)';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_LOCATION" IS '전시세부장소(DEFAULT)';

DROP TABLE "CHATTING_ROOM";

CREATE TABLE "CHATTING_ROOM" (
   "CHATTING_NO"   NUMBER      NOT NULL,
   "CH_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "OPEN_MEMBER"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHATTING_ROOM"."CH_CREATE_DATE" IS '채팅방 생성일';

COMMENT ON COLUMN "CHATTING_ROOM"."OPEN_MEMBER" IS '개설자 회원번호';

DROP TABLE "CHAT_MEMBER";

CREATE TABLE "CHAT_MEMBER" (
   "CHATTING_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHAT_MEMBER"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHAT_MEMBER"."MEMBER_NO" IS '회원번호';

DROP TABLE "NOTIFICATION";

CREATE TABLE "NOTIFICATION" (
   "NOTIFICATION_NO"   NUMBER      NOT NULL,
   "NOTIFICATION_CONTENT"   VARCHAR2(1000)      NOT NULL,
   "NOTIFICATION_CHECK"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "NOTIFICATION_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "NOTIFICATION_URL"   VARCHAR2(1000)      NOT NULL,
   "SEND_MEMBER_NO"   NUMBER      NOT NULL,
   "RECEIVE_MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_NO" IS '알림 번호';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CONTENT" IS '알림 내용';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CHECK" IS '읽음 여부(Y/N)';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_DATE" IS '알림 생성 시간';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_URL" IS '연결 페이지 주소';

COMMENT ON COLUMN "NOTIFICATION"."SEND_MEMBER_NO" IS '알림 보낸 회원번호';

COMMENT ON COLUMN "NOTIFICATION"."RECEIVE_MEMBER_NO" IS '알림 받는 회원번호';

DROP TABLE "CHATTING_MESSAGE";

CREATE TABLE "CHATTING_MESSAGE" (
   "MESSAGE_NO"   NUMBER      NOT NULL,
   "MESSAGE_CONTENT"   VARCHAR2(4000 CHAR)      NOT NULL,
   "READ_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "SEND_TIME"   DATE   DEFAULT SYSDATE   NOT NULL,
   "CHATTING_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CHATTING_MESSAGE"."MESSAGE_NO" IS '메세지 번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MESSAGE_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "CHATTING_MESSAGE"."READ_FL" IS '메세지 읽음 여부';

COMMENT ON COLUMN "CHATTING_MESSAGE"."SEND_TIME" IS '메세지 보낸 시간';

COMMENT ON COLUMN "CHATTING_MESSAGE"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MEMBER_NO" IS '회원번호';

DROP TABLE "PM_PRICE_LIST";

CREATE TABLE "PM_PRICE_LIST" (
   "PM_PRICE_TYPE"   VARCHAR2(100)      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "PM_PRICE"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PM_PRICE_LIST"."PM_PRICE_TYPE" IS '좌석 종류(전부 동일할 경우 전석)';

COMMENT ON COLUMN "PM_PRICE_LIST"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PM_PRICE_LIST"."PM_PRICE" IS '가격';

DROP TABLE "STAR";

CREATE TABLE "STAR" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "STAR"   VARCHAR2(10)      NOT NULL
);

COMMENT ON COLUMN "STAR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "STAR"."MEMBER_NO" IS '별점 남긴 회원번호';

COMMENT ON COLUMN "STAR"."STAR" IS '게시글 별점';

DROP TABLE "EXHIBITION";

CREATE TABLE "EXHIBITION" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "EXHIBIT_SUB_TITLE"   VARCHAR2(200 CHAR)      NULL,
   "EXHIBIT_SITE"   VARCHAR2(100 CHAR)      NULL,
   "EXHIBIT_DATE"   VARCHAR2(50 CHAR)      NULL,
   "EXHIBIT_CONTACT"   VARCHAR2(100 CHAR)      NOT NULL,
   "EXHIBIT_AUDIENCE"   VARCHAR2(50 CHAR)      NULL,
   "EXHIBIT_CHARGE"   NUMBER   DEFAULT 0   NOT NULL,
   "INSTITUTION_NO"   NUMBER      NOT NULL,
   "GENRE_NO"   NUMBER      NOT NULL
);


COMMENT ON COLUMN "EXHIBITION"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_SUB_TITLE" IS '전시부제목';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_SITE" IS '전시세부장소';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_DATE" IS '전시시작종료일';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_CONTACT" IS '전시문의';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_AUDIENCE" IS '전시대상연령';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_CHARGE" IS '전시관람료';

COMMENT ON COLUMN "EXHIBITION"."INSTITUTION_NO" IS '전시기관번호(SEQ_INSTITUTION_NO)';

COMMENT ON COLUMN "EXHIBITION"."GENRE_NO" IS '장르 번호(SEQ_GENRE_NO)';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
   "COMMENT_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "C_CREATE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "COMMENT_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "COMMENT_DEL_FL"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "P_COMMENT"   NUMBER      NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "COMMENT"."C_CREATE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부(N : 삭제X, Y : 삭제O)';

COMMENT ON COLUMN "COMMENT"."P_COMMENT" IS '공연 기대평 댓글 용 부모 여부';

DROP TABLE "BOARDTYPE";

CREATE TABLE "BOARDTYPE" (
   "COMMUNITY_CODE"   NUMBER      NOT NULL,
   "COMMUNITY_NAME"   VARCHAR2(20)      NOT NULL
);

COMMENT ON COLUMN "BOARDTYPE"."COMMUNITY_CODE" IS '커뮤니티 코드';

COMMENT ON COLUMN "BOARDTYPE"."COMMUNITY_NAME" IS '커뮤니티 이름';

DROP TABLE "GENRE";

CREATE TABLE "GENRE" (
   "GENRE_NO"   NUMBER      NOT NULL,
   "GENRE_NAME"   VARCHAR2(50)      NOT NULL
);

COMMENT ON COLUMN "GENRE"."GENRE_NO" IS '장르 번호(SEQ_GENRE_NO)';

COMMENT ON COLUMN "GENRE"."GENRE_NAME" IS '장르 이름';

DROP TABLE "BANK_INFO";

CREATE TABLE "BANK_INFO" (
   "REFUND_BANK"   NUMBER      NOT NULL,
   "BANK_NAME"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "BANK_INFO"."REFUND_BANK" IS '은행코드';

COMMENT ON COLUMN "BANK_INFO"."BANK_NAME" IS '은행명';

DROP TABLE "QUESTION";

CREATE TABLE "QUESTION" (
   "Q_CODE"   NUMBER      NOT NULL,
   "Q_NAME"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "QUESTION"."Q_CODE" IS '문의 번호(티켓: 1, 커뮤니티: 2, 회원/공통/기타: 3)';

COMMENT ON COLUMN "QUESTION"."Q_NAME" IS '문의 유형 이름(티켓, 커뮤니티, 회원/공통/기타)';

DROP TABLE "PAY";

CREATE TABLE "PAY" (
   "PORTONE_NO"   VARCHAR2(100)      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "SEE_DATE"   DATE      NULL,
   "PAY_MUCH"   NUMBER      NOT NULL,
   "PAY_WHAT"   VARCHAR2(30)      NOT NULL,
   "PAY_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "PAY_OK"   CHAR(1)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "PAY"."PORTONE_NO" IS '포트원에서 발급하는 고유 번호';

COMMENT ON COLUMN "PAY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PAY"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PAY"."SEE_DATE" IS '행사 기간중 언제 가는지 예약 날짜';

COMMENT ON COLUMN "PAY"."PAY_MUCH" IS '결제 금액';

COMMENT ON COLUMN "PAY"."PAY_WHAT" IS '결제 수단';

COMMENT ON COLUMN "PAY"."PAY_DATE" IS '결제 일자';

COMMENT ON COLUMN "PAY"."PAY_OK" IS '결제 완료 여부';

DROP TABLE "LIKE";

CREATE TABLE "LIKE" (
   "BOARD_NO"   NUMBER      NOT NULL,
   "MEMBER_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
   "IMG_NO"   NUMBER      NOT NULL,
   "BOARD_NO"   NUMBER      NOT NULL,
   "IMG_PATH"   VARCHAR2(500)      NOT NULL,
   "IMG_ORIG"   VARCHAR2(200)      NULL,
   "IMG_RENAME"   VARCHAR2(200)      NULL,
   "IMG_ORDER"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지번호(SEQ_IMAGE_NO)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIG" IS '원본이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '변경이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 파일 순서 번호';

ALTER TABLE "AUTHOR" ADD CONSTRAINT "PK_AUTHOR" PRIMARY KEY (
   "AUTHOR_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
   "MEMBER_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "PK_PM" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "PM_HOUSE" ADD CONSTRAINT "PK_PM_HOUSE" PRIMARY KEY (
   "PM_HOUSE_NO"
);

ALTER TABLE "CONTRIBUTOR" ADD CONSTRAINT "PK_CONTRIBUTOR" PRIMARY KEY (
   "CONTRIBUTOR_NO"
);

ALTER TABLE "INSTITUTION" ADD CONSTRAINT "PK_INSTITUTION" PRIMARY KEY (
   "INSTITUTION_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
   "CHATTING_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "PK_CHAT_MEMBER" PRIMARY KEY (
   "CHATTING_NO",
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
   "NOTIFICATION_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "PK_CHATTING_MESSAGE" PRIMARY KEY (
   "MESSAGE_NO"
);

ALTER TABLE "PM_PRICE_LIST" ADD CONSTRAINT "PK_PM_PRICE_LIST" PRIMARY KEY (
   "PM_PRICE_TYPE",
   "BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "PK_STAR" PRIMARY KEY (
   "BOARD_NO",
   "MEMBER_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "PK_EXHIBITION" PRIMARY KEY (
   "BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
   "COMMENT_NO"
);

ALTER TABLE "BOARDTYPE" ADD CONSTRAINT "PK_BOARDTYPE" PRIMARY KEY (
   "COMMUNITY_CODE"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
   "GENRE_NO"
);

ALTER TABLE "BANK_INFO" ADD CONSTRAINT "PK_BANK_INFO" PRIMARY KEY (
   "REFUND_BANK"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
   "Q_CODE"
);

ALTER TABLE "PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY (
   "PORTONE_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
   "BOARD_NO",
   "MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
   "IMG_NO"
);

ALTER TABLE "AUTHOR" ADD CONSTRAINT "FK_EXHIBITION_TO_AUTHOR_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "EXHIBITION" (
   "BOARD_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_BOARD_TO_PM_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_GENRE_TO_PM_1" FOREIGN KEY (
   "GENRE_NO"
)
REFERENCES "GENRE" (
   "GENRE_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_PM_HOUSE_TO_PM_1" FOREIGN KEY (
   "PM_HOUSE_NO"
)
REFERENCES "PM_HOUSE" (
   "PM_HOUSE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARDTYPE_TO_BOARD_1" FOREIGN KEY (
   "COMMUNITY_CODE"
)
REFERENCES "BOARDTYPE" (
   "COMMUNITY_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_QUESTION_TO_BOARD_1" FOREIGN KEY (
   "Q_CODE"
)
REFERENCES "QUESTION" (
   "Q_CODE"
);

ALTER TABLE "PAY_BACK" ADD CONSTRAINT "FK_PAY_TO_PAY_BACK_1" FOREIGN KEY (
   "PORTONE_NO"
)
REFERENCES "PAY" (
   "PORTONE_NO"
);

ALTER TABLE "PAY_BACK" ADD CONSTRAINT "FK_BANK_INFO_TO_PAY_BACK_1" FOREIGN KEY (
   "REFUND_BANK"
)
REFERENCES "BANK_INFO" (
   "REFUND_BANK"
);

ALTER TABLE "CONTRIBUTOR" ADD CONSTRAINT "FK_EXHIBITION_TO_CONTRIBUTOR_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "EXHIBITION" (
   "BOARD_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_1" FOREIGN KEY (
   "OPEN_MEMBER"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_CHAT_MEMBER_1" FOREIGN KEY (
   "CHATTING_NO"
)
REFERENCES "CHATTING_ROOM" (
   "CHATTING_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_MEMBER_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
   "SEND_MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY (
   "RECEIVE_MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "FK_CHAT_MEMBER_TO_CHATTING_MESSAGE_1" FOREIGN KEY (
   "CHATTING_NO"
)
REFERENCES "CHAT_MEMBER" (
   "CHATTING_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "FK_CHAT_MEMBER_TO_CHATTING_MESSAGE_2" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "CHAT_MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "PM_PRICE_LIST" ADD CONSTRAINT "FK_PM_TO_PM_PRICE_LIST_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "PM" (
   "BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "FK_BOARD_TO_STAR_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "FK_MEMBER_TO_STAR_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_BOARD_TO_EXHIBITION_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_INSTITUTION_TO_EXHIBITION_1" FOREIGN KEY (
   "INSTITUTION_NO"
)
REFERENCES "INSTITUTION" (
   "INSTITUTION_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_GENRE_TO_EXHIBITION_1" FOREIGN KEY (
   "GENRE_NO"
)
REFERENCES "GENRE" (
   "GENRE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "PAY" ADD CONSTRAINT "FK_MEMBER_TO_PAY_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "PAY" ADD CONSTRAINT "FK_BOARD_TO_PAY_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_BOARD_TO_LIKE_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
   "MEMBER_NO"
)
REFERENCES "MEMBER" (
   "MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
   "BOARD_NO"
)
REFERENCES "BOARD" (
   "BOARD_NO"
);

---------------------------------------------------
-- 시퀀스 자동 삭제 후 재생성 스크립트
---------------------------------------------------
-- 게시판 관련
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_CODE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_BOARD_CODE START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_IMG_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 채팅
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHATTING_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CHATTING_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 댓글
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMMENT_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_COMMENT_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 기여자
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONTRIBUTOR_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_CONTRIBUTOR_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 장르
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_GENRE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_GENRE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 하우스 (공연장 등)
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_HOUSE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_HOUSE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 기관
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INSTITUTION_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_INSTITUTION_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 회원
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEMBER_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 메시지
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MESSAGE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_MESSAGE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 결제 관련
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAY_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PAY_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PMGENRE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PMGENRE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PMIMG_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PMIMG_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PMPRICE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PMPRICE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PRICE_NO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_PRICE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
/

-- 문의
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_QUESTION_CODE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SEQUENCE SEQ_QUESTION_CODE START WITH 1 INCREMENT BY 1 NOCACHE;
/
CREATE SEQUENCE SEQ_AUTHOR_NO START WITH 1 NOCACHE; 

---------------------------------

-- 샘플 계정 추가 (user01 ~ user21)MEMBER INSERT 완성
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'user01@og.or.kr', 'pass01!',
    '일번유저', '0231532820', '06234,,서울특별시 마포구 월드컵북로 400 서울경제진흥원,,6층·8층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'user02@og.or.kr', 'pass02!',
    '이번유저', '01043214321', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'user03@og.or.kr', 'pass03!',
    '삼번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', 'user04@og.or.kr', 'pass04!',
    '사번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', 'user05@og.or.kr', 'pass05!',
    '오번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user06', 'user06@og.or.kr', 'pass06!',
    '육번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user07', 'user07@og.or.kr', 'pass07!',
    '칠번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user08', 'user08@og.or.kr', 'pass08!',
    '팔번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user09', 'user09@og.or.kr', 'pass09!',
    '구번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user10', 'user10@og.or.kr', 'pass10!',
    '한국문화정보원', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user11', 'user11@og.or.kr', 'pass11!',
    '나챗봇', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user12', 'user12@og.or.kr', 'pass12!',
    '십이번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user13', 'user13@og.or.kr', 'pass13!',
    '십삼번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user14', 'user14@og.or.kr', 'pass14!',
    '십사번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user15', 'user15@og.or.kr', 'pass15!',
    '십오번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user16', 'user16@og.or.kr', 'pass16!',
    '십육번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user17', 'user17@og.or.kr', 'pass17!',
    '십칠번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user18', 'user18@og.or.kr', 'pass18!',
    '십팔번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user19', 'user19@og.or.kr', 'pass19!',
    '십구번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user20', 'user20@og.or.kr', 'pass20!',
    '이십번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user21', 'user21@og.or.kr', 'pass21!',
    '이십일번유저', '01011112222', '06234,,서울 종로구 관철동 45-1,,9층', 'N', NULL, DEFAULT);

COMMIT;
--------------------------------------------------------------------------------------------------------
-- BOARDTYPE INSERT 
-- 게시판 종류 추가
INSERT INTO "BOARDTYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '자유 게시판');
INSERT INTO "BOARDTYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '리뷰 게시판');
INSERT INTO "BOARDTYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '전시 게시판');
INSERT INTO "BOARDTYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '공연 게시판');
INSERT INTO "BOARDTYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '문의 게시판');


-- 문의 유형 
INSERT INTO "QUESTION" VALUES(SEQ_QUESTION_CODE.NEXTVAL, '티켓');
INSERT INTO "QUESTION" VALUES(SEQ_QUESTION_CODE.NEXTVAL, '커뮤니티');
INSERT INTO "QUESTION" VALUES(SEQ_QUESTION_CODE.NEXTVAL, '회원/공동/기타');

-----------------------------------------------------------------------------------
-- 게시판 샘플 데이터 삽입
-- 자유게시판 샘플 데이터 (앞 12개 이미지 포함)
-- ==========================================
-- 자유게시판 샘플 데이터 (게시글 + 이미지 자동 삽입)
-- ==========================================
-- 자유게시판 샘플 데이터 (각 게시글에 실제 확장자 그대로 이미지 연결)
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(IMG_NO), 0) + 1 INTO v_max FROM BOARD_IMG;

    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BOARD_IMG_NO';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_BOARD_IMG_NO START WITH ' || v_max || ' INCREMENT BY 1 NOCACHE';
END;
/

commit;
BEGIN
   FOR I IN 1..187 LOOP
      INSERT INTO BOARD (
         BOARD_NO, BOARD_TITLE, BOARD_CONTENT, B_CREATE_DATE, B_UPDATE_DATE,  BOARD_COUNT,
         BOARD_DEL_FL,  MEMBER_NO,  COMMUNITY_CODE,  Q_CODE
      ) VALUES (
         SEQ_BOARD_NO.NEXTVAL,
         SEQ_BOARD_NO.CURRVAL || '번째 게시글',
         SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다.',
         SYSDATE, SYSDATE, 0, 'N',
         1,   -- MEMBER_NO 고정
         1,    -- COMMUNITY_CODE 고정
         NULL
      );
   END LOOP;
   COMMIT;
END;
/


BEGIN
   FOR i IN 1..12 LOOP
      -- 게시글 INSERT
      INSERT INTO BOARD (
         BOARD_NO, BOARD_TITLE, BOARD_CONTENT,
         B_CREATE_DATE, B_UPDATE_DATE, BOARD_COUNT,
         BOARD_DEL_FL, MEMBER_NO, COMMUNITY_CODE, Q_CODE
      ) VALUES (
         SEQ_BOARD_NO.NEXTVAL,

         CASE i
            WHEN 1 THEN '주말에 뮤지컬 보러 가실 분~?'
            WHEN 2 THEN '서울 전시회 같이 가실 분 구해요!'
            WHEN 3 THEN '오늘 콘서트 다녀왔는데 분위기 최고였어요'
            WHEN 4 THEN '전시회 후기 + 사진 몇 장 공유해요 😊'
            WHEN 5 THEN '공연 추천 좀 해주세요! 요즘 볼만한 거 있나요?'
            WHEN 6 THEN '혼자 가기 아쉬워서.. 같이 가실 분 있으신가요?'
            WHEN 7 THEN '요즘 전시회 많이 다니는데 추천 리스트 공유드려요'
            WHEN 8 THEN '뮤지컬 예매했어요!! 혹시 보신 분 후기 좀 부탁드려요'
            WHEN 9 THEN '공연 예매 꿀팁 아시는 분 있나요?'
            WHEN 10 THEN '사진전 다녀왔어요~ 색감이 너무 예뻐요'
            WHEN 11 THEN '오늘 전시회에서 찍은 사진 공유합니다📸'
            WHEN 12 THEN '이번 주말에 전시회 같이 보러 가실 분 계신가요?'
         END,

         CASE i
            WHEN 1 THEN '주말에 레미제라블 뮤지컬 보러 가려고 하는데 같이 가실 분 구해요! 시간 맞으시면 댓글 주세요 😄'
            WHEN 2 THEN '서울에서 열리는 ‘빛의 향연’ 전시회 같이 보실 분 계신가요? 혼자 가긴 좀 그래서요ㅎㅎ'
            WHEN 3 THEN '오늘 콘서트 다녀왔는데 진짜 최고였습니다..! 현장 분위기가 미쳤어요 🎶'
            WHEN 4 THEN '전시회 다녀왔는데 사진 너무 잘 나와서 공유합니다! 분위기 정말 좋아요~'
            WHEN 5 THEN '요즘 볼만한 공연 추천 좀 부탁드려요! 장르 상관없이 재밌는 거면 다 좋아요!'
            WHEN 6 THEN '공연 같이 보러 가실 분 구해요! 혼자 가기엔 좀 심심해서요 😅'
            WHEN 7 THEN '최근에 다녀온 전시회 중에서 괜찮았던 곳 몇 군데 정리해봤어요. 정보 공유해요~'
            WHEN 8 THEN '다음 주에 <지킬앤하이드> 예매했어요! 후기나 팁 있으신가요?'
            WHEN 9 THEN '공연 예매할 때 좋은 사이트나 할인 정보 아시는 분 댓글 부탁드려요 🙏'
            WHEN 10 THEN '오늘 다녀온 사진전! 색감 너무 예쁘고 조명도 환상이에요. 강추!'
            WHEN 11 THEN '전시회 사진 몇 장 올려봅니다 :) 실제로 보면 훨씬 멋져요!'
            WHEN 12 THEN '이번 주말에 전시회 같이 보러 가실 분~ 시간 맞으면 같이 가요 ☺️'
         END
         || CHR(10) || '사진 첨부했어요! 아래 이미지 참고해주세요 📷',

         SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0, 20)),
         SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0, 10)),
         TRUNC(DBMS_RANDOM.VALUE(10, 200)),
         'N',
         TRUNC(DBMS_RANDOM.VALUE(1, 6)),
         1,
         NULL
      );

      -- 실제 확장자 매핑
      DECLARE
         v_ext VARCHAR2(10);
      BEGIN
         v_ext := CASE i
                     WHEN 1 THEN '.jpg'
                     WHEN 2 THEN '.png'
                     WHEN 3 THEN '.jpg'
                     WHEN 4 THEN '.png'
                     WHEN 5 THEN '.jpg'
                     WHEN 6 THEN '.jpeg'
                     WHEN 7 THEN '.png'
                     WHEN 8 THEN '.jpeg'
                     WHEN 9 THEN '.jpg'
                     WHEN 10 THEN '.jpg'
                     WHEN 11 THEN '.jpg'
                     WHEN 12 THEN '.jpg'
                  END;

         INSERT INTO BOARD_IMG (
            IMG_NO, BOARD_NO, IMG_PATH, IMG_ORIG, IMG_RENAME, IMG_ORDER
         ) VALUES (
            SEQ_BOARD_IMG_NO.NEXTVAL,
            SEQ_BOARD_NO.CURRVAL,
            '/images/board/freeboard/',
            'image' || i || v_ext,
            'image' || i || v_ext,
            0
         );
      END;
   END LOOP;
   COMMIT;
END;
/

-------------------------------------------------------------------------
-- 문의 게시판 Q_CODE=1 더미 데이터
INSERT INTO BOARD (BOARD_NO, 
                    BOARD_TITLE, 
                    BOARD_CONTENT, 
                    B_CREATE_DATE, 
                    B_UPDATE_DATE, 
                    BOARD_COUNT, 
                    BOARD_DEL_FL, 
                    MEMBER_NO, 
                    COMMUNITY_CODE, 
                    Q_CODE)
SELECT SEQ_BOARD_NO.NEXTVAL,
        '티켓 예약은 어떻게 하나요?',
        '티켓 예약 방법을 모르겠어요!! 알려주세요ㅠㅠ',
        SYSDATE,
        SYSDATE,                            -- B_UPDATE_DATE
        0,                                  -- BOARD_COUNT (조회수)
        'N',                                -- BOARD_DEL_FL (삭제 여부)
        1,                                  -- MEMBER_NO (1~9 사이 랜덤)
        5,                                  -- COMMUNITY_CODE (1~4 랜덤)
        1
FROM DUAL
CONNECT BY LEVEL <= 100;

-- 내 문의 게시판 Q_CODE=2 더미 데이터
INSERT INTO BOARD (BOARD_NO, 
                    BOARD_TITLE, 
                    BOARD_CONTENT, 
                    B_CREATE_DATE, 
                    B_UPDATE_DATE, 
                    BOARD_COUNT, 
                    BOARD_DEL_FL, 
                    MEMBER_NO, 
                    COMMUNITY_CODE, 
                    Q_CODE)
SELECT SEQ_BOARD_NO.NEXTVAL,
        '채팅은 어떻게 하나요?',
        '채팅하고 싶어요ㅜㅜ 채팅하는 법 알려줘요!!',
        SYSDATE,
        SYSDATE,                            -- B_UPDATE_DATE
        0,                                  -- BOARD_COUNT (조회수)
        'N',                                -- BOARD_DEL_FL (삭제 여부)
        1,                                  -- MEMBER_NO (1~9 사이 랜덤)
        5,                                  -- COMMUNITY_CODE (1~4 랜덤)
        2
FROM DUAL
CONNECT BY LEVEL <= 100;

-- 내 문의 게시판 Q_CODE=3 더미 데이터
INSERT INTO BOARD (BOARD_NO, 
                    BOARD_TITLE, 
                    BOARD_CONTENT, 
                    B_CREATE_DATE, 
                    B_UPDATE_DATE, 
                    BOARD_COUNT, 
                    BOARD_DEL_FL, 
                    MEMBER_NO, 
                    COMMUNITY_CODE, 
                    Q_CODE)
SELECT SEQ_BOARD_NO.NEXTVAL,
        '회원 탈퇴 어떻게 하나요?',
        '회원 탈퇴 버튼이 어디있는지 모르겠어요!! 알려주세요ㅠㅠ',
        SYSDATE,
        SYSDATE,                            -- B_UPDATE_DATE
        0,                                  -- BOARD_COUNT (조회수)
        'N',                                -- BOARD_DEL_FL (삭제 여부)
        1,                                  -- MEMBER_NO (1~9 사이 랜덤)
        5,                                  -- COMMUNITY_CODE (1~4 랜덤)
        3
FROM DUAL
CONNECT BY LEVEL <= 100;

-----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_GENRE_NO START WITH 1 NOCACHE;
INSERT INTO GENRE VALUES(1, '연극');
INSERT INTO GENRE VALUES(2, '뮤지컬');
INSERT INTO GENRE VALUES(3, '음악');
INSERT INTO GENRE VALUES(4, '무용');
INSERT INTO GENRE VALUES(5, '서커스/마술');
INSERT INTO GENRE VALUES(6, '복합');


DROP SEQUENCE SEQ_GENRE_NO;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_GENRE_NO START WITH 700 NOCACHE;
-- 게시판 종류 추가
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '현대미술');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '미디어아트');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '사진전');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '설치미술');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '전통미술');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '민속미술');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '장르불분명(Unclassified)');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '복합장르(Hybrid Art)');
INSERT INTO "GENRE" VALUES(SEQ_GENRE_NO.NEXTVAL, '기획전시(Curated Exhibition)');



-- 게시판 종류 추가
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립경주박물관', '054-740-7548', '본관');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립공주박물관', '041-850-6300', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립광주박물관', '062-570-7800', '전시관 1층 전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립김해박물관', '055-320-6800', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립대구박물관', '053-760-8580', '본관중앙홀');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립박물관문화재단', '1544-5955', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립부여박물관', '041-833-8562', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립아시아문화전당', '051-704-9270', '예술극장 로비');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립어린이청소년도서관', '02-3413-4800', 'None');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립익산박물관', '063-830-0900', '미륵사지유물전시관');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립제주박물관', '학예연구실 이재호 학예연구사 (064-720-8104)', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립중앙박물관', '02-2077-9540', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립진주박물관', '055-742-5951', '두암관');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립청주박물관', '043-229-6500', '청련관');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립춘천박물관', '033-260-1500', '본관 중앙홀');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립한글박물관', '02-2124-6200', '기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '국립현대미술관', '02-3701-9500', '과천');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '대한민국역사박물관', '02-3703-9200', '1층 기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '예술의전당', '02-325-1077', 'None');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '태권도진흥재단', '063-320-0115', 'None');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '한국영상자료원', '02-3153-2001', '한국영화박물관 기획전시실');
INSERT INTO "INSTITUTION" VALUES(SEQ_INSTITUTION_NO.NEXTVAL, '한국예술종합학교', '02-746-9642', 'K');

COMMIT;

-- 1. 채팅방 개설
INSERT INTO CHATTING_ROOM (
    CHATTING_NO,
    OPEN_MEMBER
) VALUES (
    SEQ_CHATTING_NO.NEXTVAL,
    1 -- 회원 번호
);


INSERT INTO CHAT_MEMBER (CHATTING_NO, MEMBER_NO)
VALUES (1, 4);

INSERT INTO CHAT_MEMBER (CHATTING_NO, MEMBER_NO)
VALUES (1, 1);


INSERT INTO CHATTING_MESSAGE (MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO)
VALUES (SEQ_MESSAGE_NO.NEXTVAL, '안녕하세요! 공연 관련 문의드립니다 😊', 'N', SYSDATE - INTERVAL '5' MINUTE, 1, 1);

INSERT INTO CHATTING_MESSAGE (MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO)
VALUES (SEQ_MESSAGE_NO.NEXTVAL, '네, 어떤 공연을 말씀하시는 건가요?', 'N', SYSDATE - INTERVAL '4' MINUTE, 1, 4);

INSERT INTO CHATTING_MESSAGE (MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO)
VALUES (SEQ_MESSAGE_NO.NEXTVAL, '이번 주말에 있는 "레미제라블" 예매하려고요!', 'N', SYSDATE - INTERVAL '3' MINUTE, 1, 1);

INSERT INTO CHATTING_MESSAGE (MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO)
VALUES (SEQ_MESSAGE_NO.NEXTVAL, '아! 그 공연 예매는 오픈 중이에요. 링크 보내드릴까요?', 'N', SYSDATE - INTERVAL '2' MINUTE, 1, 4);

INSERT INTO CHATTING_MESSAGE (MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO)
VALUES (SEQ_MESSAGE_NO.NEXTVAL, '좋아요! 감사합니다 🙏', 'N', SYSDATE - INTERVAL '1' MINUTE, 1, 1);

COMMIT;
-------------------------------------------------------
-- 팀 채팅방 생성 (CHATTING_ROOM)
-------------------------------------------------------
INSERT INTO CHATTING_ROOM (
    CHATTING_NO,
    OPEN_MEMBER
) VALUES (
    SEQ_CHATTING_NO.NEXTVAL,
    1   -- 방 개설자 (user1)
);

-- 생성된 방 번호 확인
SELECT SEQ_CHATTING_NO.CURRVAL AS TEAM_ROOM_NO FROM DUAL;
-- 👉 예: 2번 채팅방이라고 가정


-------------------------------------------------------
-- 팀 채팅 멤버 추가 (CHAT_MEMBER)
-------------------------------------------------------
INSERT INTO CHAT_MEMBER (CHATTING_NO, MEMBER_NO) VALUES (2, 1);
INSERT INTO CHAT_MEMBER (CHATTING_NO, MEMBER_NO) VALUES (2, 2);
INSERT INTO CHAT_MEMBER (CHATTING_NO, MEMBER_NO) VALUES (2, 3);


-------------------------------------------------------
-- 팀 채팅 메시지 (CHATTING_MESSAGE)
-------------------------------------------------------
INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '안녕하세요 팀원들! 이번 주 공연 준비 일정 공유드려요.',
    'N',
    SYSDATE - INTERVAL '10' MINUTE,
    2,
    1
);

INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '네! 공연 대본은 어제 다 정리했습니다.',
    'N',
    SYSDATE - INTERVAL '9' MINUTE,
    2,
    2
);

INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '좋아요 👍 오늘 리허설 몇 시부터 할까요?',
    'N',
    SYSDATE - INTERVAL '8' MINUTE,
    2,
    3
);

INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '6시쯤 괜찮을까요? 장소는 지난번 연습실로!',
    'N',
    SYSDATE - INTERVAL '7' MINUTE,
    2,
    1
);

INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '네 6시에 봬요~',
    'N',
    SYSDATE - INTERVAL '6' MINUTE,
    2,
    2
);

INSERT INTO CHATTING_MESSAGE (
    MESSAGE_NO, MESSAGE_CONTENT, READ_FL, SEND_TIME, CHATTING_NO, MEMBER_NO
) VALUES (
    SEQ_MESSAGE_NO.NEXTVAL,
    '확인했습니다. 다들 수고해요!',
    'N',
    SYSDATE - INTERVAL '5' MINUTE,
    2,
    3
);

COMMIT;

--------------------------------------------------------
-- 5️⃣ 리뷰게시판 더미데이터 삽입 (COMMUNITY_CODE = 2)
--------------------------------------------------------
BEGIN
   FOR i IN 1..12 LOOP
      INSERT INTO BOARD (
         BOARD_NO, BOARD_TITLE, BOARD_CONTENT,
         B_CREATE_DATE, B_UPDATE_DATE, BOARD_COUNT,
         BOARD_DEL_FL, MEMBER_NO, COMMUNITY_CODE, Q_CODE
      ) VALUES (
         SEQ_BOARD_NO.NEXTVAL,

         CASE i
            WHEN 1 THEN '뮤지컬 <레미제라블> 감동 후기'
            WHEN 2 THEN '전시회 <빛의 향연> 진짜 색감 미쳤어요✨'
            WHEN 3 THEN '콘서트 후기 - 귀호강 제대로 했습니다 🎵'
            WHEN 4 THEN '사진전 <청춘의 기록> 감성 폭발 📸'
            WHEN 5 THEN '무용 공연 <흔적> 보고 온 후기'
            WHEN 6 THEN '아이랑 함께 본 전시 <우리의 시간>'
            WHEN 7 THEN '뮤지컬 <지킬앤하이드> 연기력 대박...'
            WHEN 8 THEN '전시 <시간의 틈> - 조용한 감동'
            WHEN 9 THEN '클래식 공연 첫 관람 후기 🎻'
            WHEN 10 THEN '전시 <빛과 공간> 관람 후기'
            WHEN 11 THEN '오늘 다녀온 전시회 사진 공유합니다 📷'
            WHEN 12 THEN '공연 추천 및 후기 공유해요 🎭'
         END,

         CASE i
            WHEN 1 THEN '넘버 하나하나가 너무 완벽했어요. 마지막 장면에서 눈물났습니다.'
            WHEN 2 THEN '빛의 색감이 공간을 완전히 바꾸네요. 사진 백 장 찍었어요.'
            WHEN 3 THEN '가수 실력이 미쳤습니다. 라이브로 듣는 감동은 다릅니다!'
            WHEN 4 THEN '감성 사진전이라 기대했는데 진짜 기대 이상이었어요.'
            WHEN 5 THEN '무용수들의 몸짓이 예술 그 자체였습니다. 감동받았어요.'
            WHEN 6 THEN '아이와 함께 보기에도 좋았고, 구성도 알차네요.'
            WHEN 7 THEN '주인공 연기력에 소름... 다음에도 꼭 볼 거예요.'
            WHEN 8 THEN '잔잔한 음악과 조명이 어우러져 힐링 그 자체였어요.'
            WHEN 9 THEN '처음 본 클래식 공연이었는데, 오케스트라의 웅장함에 감탄했습니다.'
            WHEN 10 THEN '빛과 그림자의 조화가 너무 아름다웠어요. 사진도 너무 잘 나옵니다.'
            WHEN 11 THEN '오늘 전시회 다녀왔는데 분위기가 너무 좋아서 공유해요 😊'
            WHEN 12 THEN '요즘 본 공연 중 최고였어요. 다들 추천합니다!'
         END
         ,

         SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0, 15)),
         SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0, 5)),
         TRUNC(DBMS_RANDOM.VALUE(50, 500)),
         'N',
         TRUNC(DBMS_RANDOM.VALUE(1, 10)),  -- 회원번호 1~10 랜덤
         2,                                 -- 리뷰게시판 코드
         NULL
      );

      -- 이미지 INSERT
      DECLARE
         v_ext VARCHAR2(10);
      BEGIN
         v_ext := CASE i
                     WHEN 1 THEN '.jpg'
                     WHEN 2 THEN '.png'
                     WHEN 3 THEN '.jpg'
                     WHEN 4 THEN '.png'
                     WHEN 5 THEN '.jpg'
                     WHEN 6 THEN '.jpeg'
                     WHEN 7 THEN '.png'
                     WHEN 8 THEN '.jpeg'
                     WHEN 9 THEN '.jpg'
                     WHEN 10 THEN '.jpg'
                     WHEN 11 THEN '.jpg'
                     WHEN 12 THEN '.jpg'
                  END;

         INSERT INTO BOARD_IMG (
            IMG_NO, BOARD_NO, IMG_PATH, IMG_ORIG, IMG_RENAME, IMG_ORDER
         ) VALUES (
            SEQ_BOARD_IMG_NO.NEXTVAL,
            SEQ_BOARD_NO.CURRVAL,
            '/images/board/reviewboard/',
            'image' || i || v_ext,          -- 원본 파일명
            '20251017_image' || i || v_ext, -- 날짜 붙은 파일명
            0
         );
      END;
   END LOOP;
   COMMIT;
END;
/

commit;

--------------------------------------------------------
---------------------- [ 2025/11/08 ]-------------------
----------------------------------------------------------
---- [채팅방 나가기] CHATTING_MEMBER 삭제 (1:1 경우 두명 다 삭제)
--DELETE FROM CHAT_MEMBER
--WHERE CHATTING_NO = #{chattingNo} AND MEMBER_NO = #{memberNo}
--
--DELETE FROM CHAT_MEMBER
--WHERE CHATTING_NO = #{chattingNo} AND MEMBER_NO = #{memberNo}
--
---- 채팅방에 남은 멤버 수 조회 
--SELECT COUNT(*) FROM CHAT_MEMBER WHERE CHATTING_NO = #{chattingNo}
--
---- [빈 채팅방 삭제 ]
---- 먼저 모든 메시지 CHATTING_MESSAGE에서 삭제
--DELETE FROM CHATTING_MESSAGE WHERE CHATTING_NO = #{chattingNo}
--        
---- 그다음, CHATTING_ROOM (chattingNo) 삭제
--DELETE FROM CHATTING_ROOM WHERE CHATTING_NO = #{chattingNo}

-- COMMIT;
--------------------------------------------------------
-- [채팅방 나가기] CHATTING_MEMBER 삭제 (1:1 경우 두명 다 삭제) 예
DELETE FROM CHAT_MEMBER WHERE CHATTING_NO = 5 AND MEMBER_NO =14;
DELETE FROM CHAT_MEMBER WHERE CHATTING_NO = 5 AND MEMBER_NO =11;

-- 채팅방에 남은 멤버 수 조회 
SELECT COUNT(*) FROM CHAT_MEMBER WHERE CHATTING_NO = 5;

-- [빈 채팅방 삭제 ]
-- 먼저 모든 메시지 CHATTING_MESSAGE에서 삭제
DELETE FROM CHATTING_MESSAGE WHERE CHATTING_NO = 5;
        
-- 그다음, CHATTING_ROOM (chattingNo) 삭제
DELETE FROM CHATTING_ROOM WHERE CHATTING_NO = 5;

COMMIT;
