-- 관리자 계정으로 해라
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 계정 생성
CREATE USER moa IDENTIFIED BY moa1234;

-- 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO moa;

-- 객체 생성 공간 할당
ALTER USER moa DEFAULT TABLESPACE SYSTEM
QUOTA UNLIMITED ON SYSTEM;

----------------------------------------------------
DROP TABLE "AUTHOR";

CREATE TABLE "AUTHOR" (
	"AUTHOR_NO"	NUMBER		NOT NULL,
	"AUTHOR_NAME"	VARCHAR2(500 CHAR)		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "AUTHOR"."AUTHOR_NO" IS '전시작가번호(SEQ_AUTHOR_NO)';

COMMENT ON COLUMN "AUTHOR"."AUTHOR_NAME" IS '전시작가이름';

COMMENT ON COLUMN "AUTHOR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(30)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(30)		NOT NULL,
	"MEMBER_NICKNAME"	VARCHAR2(30)		NOT NULL,
	"MEMBER_TEL"	VARCHAR2(12)		NOT NULL,
	"MEMBER_ADDR"	VARCHAR2(150)		NULL,
	"MEMBER_ADMIN"	CHAR(1)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADMIN" IS '관리자 로그인 여부(일반: N, 관리자: Y)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부(일반: N 탈퇴: Y)';

DROP TABLE "PM";

CREATE TABLE "PM" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"GENRE_NO"	NUMBER		NOT NULL,
	"PM_START_TIME"	DATE		NOT NULL,
	"PM_END_TIME"	DATE		NOT NULL,
	"PM_PLAYTIME"	VARCHAR2(500)		NOT NULL,
	"PM_HOUSE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PM"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PM"."GENRE_NO" IS 'SEQ_GENRE_NO';

COMMENT ON COLUMN "PM"."PM_START_TIME" IS '공연 시작일';

COMMENT ON COLUMN "PM"."PM_END_TIME" IS '공연 종료일';

COMMENT ON COLUMN "PM"."PM_PLAYTIME" IS '상영 시간';

COMMENT ON COLUMN "PM"."PM_HOUSE_NO" IS '공연 시설 번호';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(300 CHAR)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000 CHAR)		NULL,
	"B_CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"B_UPDATE_DATE"	DATE		NULL,
	"BOARD_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NULL,
	"COMMUNITY_CODE"	NUMBER		NOT NULL,
	"Q_CODE"	NUMBER	DEFAULT 1	NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."B_CREATE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."B_UPDATE_DATE" IS '게시글 최종 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_COUNT" IS '게시글 조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글 삭제 여부';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."Q_CODE" IS '문의 번호(티켓: 1, 커뮤니티: 2, 회원/공통/기타: 3)';

DROP TABLE "PAY_BACK";

CREATE TABLE "PAY_BACK" (
	"PORTONE_NO"	VARCHAR2(100)		NOT NULL,
	"REFUND_HOLDER"	VARCHAR2(10)		NOT NULL,
	"REFUND_ACCOUNT"	NUMBER		NOT NULL,
	"REFUND_BANK"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PAY_BACK"."PORTONE_NO" IS '포트원에서 발급하는 고유 번호';

COMMENT ON COLUMN "PAY_BACK"."REFUND_HOLDER" IS '환불 수령계좌 예금주';

COMMENT ON COLUMN "PAY_BACK"."REFUND_ACCOUNT" IS '환불 수령계좌 번호';

COMMENT ON COLUMN "PAY_BACK"."REFUND_BANK" IS '은행 코드';

DROP TABLE "PM_HOUSE";

CREATE TABLE "PM_HOUSE" (
	"PM_HOUSE_NO"	NUMBER		NOT NULL,
	"PM_HOUSE_NAME"	VARCHAR2(200)		NOT NULL,
	"PM_HOUSE_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"PM_HOUSE_LAT"	BINARY_DOUBLE		NOT NULL,
	"PM_HOUSE_LONG"	BINARY_DOUBLE		NOT NULL,
	"PM_HOUSE_WEBSITE"	VARCHAR2(300)		NOT NULL,
	"PM_HOUSE_HOME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_NO" IS 'SEQ_HOUSE_NO';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_NAME" IS '시설 이름';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_ADDRESS" IS '시설 주소';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_LAT" IS '시설 위도';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_LONG" IS '시설 경도';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_WEBSITE" IS '시설 홈페이지';

COMMENT ON COLUMN "PM_HOUSE"."PM_HOUSE_HOME" IS '시설 전화번호';

DROP TABLE "CONTRIBUTOR";

CREATE TABLE "CONTRIBUTOR" (
	"CONTRIBUTOR_NO"	NUMBER		NOT NULL,
	"EXHIBIT_HOST"	VARCHAR2(200 CHAR)		NULL,
	"EXHIBIT_SUPPORT"	VARCHAR2(200 CHAR)		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CONTRIBUTOR"."CONTRIBUTOR_NO" IS '전시주최후원번호(SEQ_CONTRIBUTOR_NO)';

COMMENT ON COLUMN "CONTRIBUTOR"."EXHIBIT_HOST" IS '전시주최';

COMMENT ON COLUMN "CONTRIBUTOR"."EXHIBIT_SUPPORT" IS '전시후원';

COMMENT ON COLUMN "CONTRIBUTOR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "INSTITUTION";

CREATE TABLE "INSTITUTION" (
	"INSTITUTION_NO"	NUMBER		NOT NULL,
	"EXHIBIT_INST_NAME"	VARCHAR(200 CHAR)		NOT NULL,
	"EXHIBIT_INST_TEL"	VARCHAR2(50 CHAR)		NOT NULL,
	"EXHIBIT_LOCATION"	VARCHAR2(100 CHAR)		NULL
);

COMMENT ON COLUMN "INSTITUTION"."INSTITUTION_NO" IS '전시기관번호(SEQ_INSTITUTION_NO)';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_INST_NAME" IS '전시기관이름';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_INST_TEL" IS '전시기관문의대표전화번호(DEFAULT)';

COMMENT ON COLUMN "INSTITUTION"."EXHIBIT_LOCATION" IS '전시세부장소(DEFAULT)';

DROP TABLE "CHATTING_ROOM";

CREATE TABLE "CHATTING_ROOM" (
	"CHATTING_NO"	NUMBER		NOT NULL,
	"CH_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"OPEN_MEMBER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_ROOM"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHATTING_ROOM"."CH_CREATE_DATE" IS '채팅방 생성일';

COMMENT ON COLUMN "CHATTING_ROOM"."OPEN_MEMBER" IS '개설자 회원번호';

DROP TABLE "CHAT_MEMBER";

CREATE TABLE "CHAT_MEMBER" (
	"CHATTING_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT_MEMBER"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHAT_MEMBER"."MEMBER_NO" IS '회원번호';

DROP TABLE "NOTIFICATION";

CREATE TABLE "NOTIFICATION" (
	"NOTIFICATION_NO"	NUMBER		NOT NULL,
	"NOTIFICATION_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"NOTIFICATION_CHECK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"NOTIFICATION_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTIFICATION_URL"	VARCHAR2(1000)		NOT NULL,
	"SEND_MEMBER_NO"	NUMBER		NOT NULL,
	"RECEIVE_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_NO" IS '알림 번호';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CONTENT" IS '알림 내용';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CHECK" IS '읽음 여부(Y/N)';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_DATE" IS '알림 생성 시간';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_URL" IS '연결 페이지 주소';

COMMENT ON COLUMN "NOTIFICATION"."SEND_MEMBER_NO" IS '알림 보낸 회원번호';

COMMENT ON COLUMN "NOTIFICATION"."RECEIVE_MEMBER_NO" IS '알림 받는 회원번호';

DROP TABLE "CHATTING_MESSAGE";

CREATE TABLE "CHATTING_MESSAGE" (
	"MESSAGE_NO"	NUMBER		NOT NULL,
	"MESSAGE_CONTENT"	VARCHAR2(4000 CHAR)		NOT NULL,
	"READ_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"SEND_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CHATTING_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHATTING_MESSAGE"."MESSAGE_NO" IS '메세지 번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MESSAGE_CONTENT" IS '메세지 내용';

COMMENT ON COLUMN "CHATTING_MESSAGE"."READ_FL" IS '메세지 읽음 여부';

COMMENT ON COLUMN "CHATTING_MESSAGE"."SEND_TIME" IS '메세지 보낸 시간';

COMMENT ON COLUMN "CHATTING_MESSAGE"."CHATTING_NO" IS '채팅방 번호';

COMMENT ON COLUMN "CHATTING_MESSAGE"."MEMBER_NO" IS '회원번호';

DROP TABLE "PM_PRICE_LIST";

CREATE TABLE "PM_PRICE_LIST" (
	"PM_PRICE_TYPE"	VARCHAR2(100)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"PM_PRICE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "PM_PRICE_LIST"."PM_PRICE_TYPE" IS '좌석 종류(전부 동일할 경우 전석)';

COMMENT ON COLUMN "PM_PRICE_LIST"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PM_PRICE_LIST"."PM_PRICE" IS '가격';

DROP TABLE "STAR";

CREATE TABLE "STAR" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STAR"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "STAR"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "STAR"."MEMBER_NO" IS '별점 남긴 회원번호';

COMMENT ON COLUMN "STAR"."STAR" IS '게시글 별점';

DROP TABLE "EXHIBITION";

CREATE TABLE "EXHIBITION" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"EXHIBIT_SUB_TITLE"	VARCHAR2(200 CHAR)		NULL,
	"EXHIBIT_SITE"	VARCHAR2(100 CHAR)		NULL,
	"EXHIBIT_DATE"	VARCHAR2(50 CHAR)		NULL,
	"EXHIBIT_CONTACT"	VARCHAR2(100 CHAR)		NOT NULL,
	"EXHIBIT_AUDIENCE"	VARCHAR2(50 CHAR)		NULL,
	"EXHIBIT_CHARGE"	NUMBER	DEFAULT 0	NOT NULL,
	"INSTITUTION_NO"	NUMBER		NOT NULL,
	"GENRE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EXHIBITION"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_SUB_TITLE" IS '전시부제목';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_SITE" IS '전시세부장소';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_DATE" IS '전시시작종료일';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_CONTACT" IS '전시문의';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_AUDIENCE" IS '전시대상연령';

COMMENT ON COLUMN "EXHIBITION"."EXHIBIT_CHARGE" IS '전시관람료';

COMMENT ON COLUMN "EXHIBITION"."INSTITUTION_NO" IS '전시기관번호(SEQ_INSTITUTION_NO)';

COMMENT ON COLUMN "EXHIBITION"."GENRE_NO" IS '장르 번호(SEQ_GENRE_NO)';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"C_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"P_COMMENT"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "COMMENT"."C_CREATE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부(N : 삭제X, Y : 삭제O)';

COMMENT ON COLUMN "COMMENT"."P_COMMENT" IS '공연 기대평 댓글 용 부모 여부';

DROP TABLE "BOARDTYPE";

CREATE TABLE "BOARDTYPE" (
	"COMMUNITY_CODE"	NUMBER		NOT NULL,
	"COMMUNITY_NAME"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARDTYPE"."COMMUNITY_CODE" IS '커뮤니티 코드';

COMMENT ON COLUMN "BOARDTYPE"."COMMUNITY_NAME" IS '커뮤니티 이름';

DROP TABLE "GENRE";

CREATE TABLE "GENRE" (
	"GENRE_NO"	NUMBER		NOT NULL,
	"GENRE_NAME"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "GENRE"."GENRE_NO" IS '장르 번호(SEQ_GENRE_NO)';

COMMENT ON COLUMN "GENRE"."GENRE_NAME" IS '장르 이름';

DROP TABLE "BANK_INFO";

CREATE TABLE "BANK_INFO" (
	"REFUND_BANK"	NUMBER		NOT NULL,
	"BANK_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "BANK_INFO"."REFUND_BANK" IS '은행코드';

COMMENT ON COLUMN "BANK_INFO"."BANK_NAME" IS '은행명';

DROP TABLE "QUESTION";

CREATE TABLE "QUESTION" (
	"Q_CODE"	NUMBER		NOT NULL,
	"Q_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "QUESTION"."Q_CODE" IS '문의 번호(티켓: 1, 커뮤니티: 2, 회원/공통/기타: 3)';

COMMENT ON COLUMN "QUESTION"."Q_NAME" IS '문의 유형 이름(티켓, 커뮤니티, 회원/공통/기타)';

DROP TABLE "PAY";

CREATE TABLE "PAY" (
	"PORTONE_NO"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"SEE_DATE"	DATE		NULL,
	"PAY_MUCH"	NUMBER		NOT NULL,
	"PAY_WHAT"	VARCHAR2(30)		NOT NULL,
	"PAY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PAY_OK"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "PAY"."PORTONE_NO" IS '포트원에서 발급하는 고유 번호';

COMMENT ON COLUMN "PAY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "PAY"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "PAY"."SEE_DATE" IS '행사 기간중 언제 가는지 예약 날짜';

COMMENT ON COLUMN "PAY"."PAY_MUCH" IS '결제 금액';

COMMENT ON COLUMN "PAY"."PAY_WHAT" IS '결제 수단';

COMMENT ON COLUMN "PAY"."PAY_DATE" IS '결제 일자';

COMMENT ON COLUMN "PAY"."PAY_OK" IS '결제 완료 여부';

DROP TABLE "LIKE";

CREATE TABLE "LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(500)		NOT NULL,
	"IMG_ORIG"	VARCHAR2(200)		NULL,
	"IMG_RENAME"	VARCHAR2(200)		NULL,
	"IMG_ORDER"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지번호(SEQ_IMAGE_NO)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIG" IS '원본이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '변경이미지명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 파일 순서 번호';

ALTER TABLE "AUTHOR" ADD CONSTRAINT "PK_AUTHOR" PRIMARY KEY (
	"AUTHOR_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "PK_PM" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "PM_HOUSE" ADD CONSTRAINT "PK_PM_HOUSE" PRIMARY KEY (
	"PM_HOUSE_NO"
);

ALTER TABLE "CONTRIBUTOR" ADD CONSTRAINT "PK_CONTRIBUTOR" PRIMARY KEY (
	"CONTRIBUTOR_NO"
);

ALTER TABLE "INSTITUTION" ADD CONSTRAINT "PK_INSTITUTION" PRIMARY KEY (
	"INSTITUTION_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY (
	"CHATTING_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "PK_CHAT_MEMBER" PRIMARY KEY (
	"CHATTING_NO",
	"MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
	"NOTIFICATION_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "PK_CHATTING_MESSAGE" PRIMARY KEY (
	"MESSAGE_NO"
);

ALTER TABLE "PM_PRICE_LIST" ADD CONSTRAINT "PK_PM_PRICE_LIST" PRIMARY KEY (
	"PM_PRICE_TYPE",
	"BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "PK_STAR" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "PK_EXHIBITION" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "BOARDTYPE" ADD CONSTRAINT "PK_BOARDTYPE" PRIMARY KEY (
	"COMMUNITY_CODE"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_NO"
);

ALTER TABLE "BANK_INFO" ADD CONSTRAINT "PK_BANK_INFO" PRIMARY KEY (
	"REFUND_BANK"
);

ALTER TABLE "QUESTION" ADD CONSTRAINT "PK_QUESTION" PRIMARY KEY (
	"Q_CODE"
);

ALTER TABLE "PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY (
	"PORTONE_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "AUTHOR" ADD CONSTRAINT "FK_EXHIBITION_TO_AUTHOR_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "EXHIBITION" (
	"BOARD_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_BOARD_TO_PM_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_GENRE_TO_PM_1" FOREIGN KEY (
	"GENRE_NO"
)
REFERENCES "GENRE" (
	"GENRE_NO"
);

ALTER TABLE "PM" ADD CONSTRAINT "FK_PM_HOUSE_TO_PM_1" FOREIGN KEY (
	"PM_HOUSE_NO"
)
REFERENCES "PM_HOUSE" (
	"PM_HOUSE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARDTYPE_TO_BOARD_1" FOREIGN KEY (
	"COMMUNITY_CODE"
)
REFERENCES "BOARDTYPE" (
	"COMMUNITY_CODE"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_QUESTION_TO_BOARD_1" FOREIGN KEY (
	"Q_CODE"
)
REFERENCES "QUESTION" (
	"Q_CODE"
);

ALTER TABLE "PAY_BACK" ADD CONSTRAINT "FK_PAY_TO_PAY_BACK_1" FOREIGN KEY (
	"PORTONE_NO"
)
REFERENCES "PAY" (
	"PORTONE_NO"
);

ALTER TABLE "PAY_BACK" ADD CONSTRAINT "FK_BANK_INFO_TO_PAY_BACK_1" FOREIGN KEY (
	"REFUND_BANK"
)
REFERENCES "BANK_INFO" (
	"REFUND_BANK"
);

ALTER TABLE "CONTRIBUTOR" ADD CONSTRAINT "FK_EXHIBITION_TO_CONTRIBUTOR_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "EXHIBITION" (
	"BOARD_NO"
);

ALTER TABLE "CHATTING_ROOM" ADD CONSTRAINT "FK_MEMBER_TO_CHATTING_ROOM_1" FOREIGN KEY (
	"OPEN_MEMBER"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_CHATTING_ROOM_TO_CHAT_MEMBER_1" FOREIGN KEY (
	"CHATTING_NO"
)
REFERENCES "CHATTING_ROOM" (
	"CHATTING_NO"
);

ALTER TABLE "CHAT_MEMBER" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_MEMBER_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
	"SEND_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY (
	"RECEIVE_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "FK_CHAT_MEMBER_TO_CHATTING_MESSAGE_1" FOREIGN KEY (
	"CHATTING_NO"
)
REFERENCES "CHAT_MEMBER" (
	"CHATTING_NO"
);

ALTER TABLE "CHATTING_MESSAGE" ADD CONSTRAINT "FK_CHAT_MEMBER_TO_CHATTING_MESSAGE_2" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "CHAT_MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PM_PRICE_LIST" ADD CONSTRAINT "FK_PM_TO_PM_PRICE_LIST_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "PM" (
	"BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "FK_BOARD_TO_STAR_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "STAR" ADD CONSTRAINT "FK_MEMBER_TO_STAR_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_BOARD_TO_EXHIBITION_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_INSTITUTION_TO_EXHIBITION_1" FOREIGN KEY (
	"INSTITUTION_NO"
)
REFERENCES "INSTITUTION" (
	"INSTITUTION_NO"
);

ALTER TABLE "EXHIBITION" ADD CONSTRAINT "FK_GENRE_TO_EXHIBITION_1" FOREIGN KEY (
	"GENRE_NO"
)
REFERENCES "GENRE" (
	"GENRE_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "PAY" ADD CONSTRAINT "FK_MEMBER_TO_PAY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "PAY" ADD CONSTRAINT "FK_BOARD_TO_PAY_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_BOARD_TO_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);





commit;




SELECT SEQUENCE_NAME FROM USER_SEQUENCES;
-- SEQ_BOARD_NO
-- SEQ_HOUSE_NO
-- SEQ_IMAGE_NO

CREATE SEQUENCE SEQ_BOARD_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HOUSE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_IMAGE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE BOARD MODIFY MEMBER_NO NUMBER NULL;


INSERT INTO BOARDTYPE (COMMUNITY_CODE, COMMUNITY_NAME)
VALUES (4, '공연게시판');

INSERT INTO QUESTION (Q_CODE, Q_NAME)
VALUES (9, '안씀');

commit;

----------------------------------------------------------------------

commit;

DROP TABLE "PMAPI";

CREATE TABLE "PMAPI" (
	"MT20ID"	VARCHAR2(100)		NULL,
	"BOARD_TITLE"	VARCHAR2(300)		NULL,
	"B_CREATE_DATE"	DATE		NULL,
	"GENRE_NO"	NUMBER		NULL,
	"GENRE_NAME"	VARCHAR2(50)		NULL,
	"PM_START_TIME"	DATE		NULL,
	"PM_END_TIME"	DATE		NULL,
	"PM_PLAYTIME"	VARCHAR2(500)		NULL,
	"MT10ID"	VARCHAR2(100)		NULL,
	"PM_HOUSE_NAME"	VARCHAR2(200)		NULL,
	"PM_HOUSE_ADDRESS"	VARCHAR2(500)		NULL,
	"PM_HOUSE_LAT"	BINARY_DOUBLE		NULL,
	"PM_HOUSE_LONG"	BINARY_DOUBLE		NULL,
	"PM_HOUSE_WEBSITE"	VARCHAR2(300)		NULL,
	"PM_HOUSE_HOME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PMAPI"."MT20ID" IS 'mt20id';

COMMENT ON COLUMN "PMAPI"."BOARD_TITLE" IS 'prfnm';

COMMENT ON COLUMN "PMAPI"."B_CREATE_DATE" IS 'updatedate';

COMMENT ON COLUMN "PMAPI"."GENRE_NO" IS 'SEQ_GENRE_NO';

COMMENT ON COLUMN "PMAPI"."GENRE_NAME" IS 'genrenm';

COMMENT ON COLUMN "PMAPI"."PM_START_TIME" IS 'prfpdfrom';

COMMENT ON COLUMN "PMAPI"."PM_END_TIME" IS 'prfpdto';

COMMENT ON COLUMN "PMAPI"."PM_PLAYTIME" IS 'prfruntime';

COMMENT ON COLUMN "PMAPI"."MT10ID" IS 'mt10id';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_NAME" IS 'fcltynm + prfplcnm';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_ADDRESS" IS 'adres';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_LAT" IS 'la';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_LONG" IS 'lo';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_WEBSITE" IS 'relateurl';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_HOME" IS 'telno';

DROP TABLE "PMAPI_IMG";

CREATE TABLE "PMAPI_IMG" (
	"PMIMG_NO"	NUMBER		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"IMG_PATH"	VARCHAR2(500)		NULL,
	"MT20ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PMAPI_IMG"."PMIMG_NO" IS 'SEQ_PMIMG_NO';

COMMENT ON COLUMN "PMAPI_IMG"."IMG_ORDER" IS 'poster=0, styurls=1~n';

COMMENT ON COLUMN "PMAPI_IMG"."IMG_PATH" IS 'poster, styurl';

COMMENT ON COLUMN "PMAPI_IMG"."MT20ID" IS 'mt20id';

DROP TABLE "PMAPI_PRICE";

CREATE TABLE "PMAPI_PRICE" (
	"PMPRICE_NO"	NUMBER		NOT NULL,
	"PM_PRICE_TYPE"	VARCHAR2(100)		NULL,
	"PM_PRICE"	NUMBER		NULL,
	"MT20ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PMAPI_PRICE"."PMPRICE_NO" IS 'SEQ_PMPRICE_NO';

COMMENT ON COLUMN "PMAPI_PRICE"."PM_PRICE_TYPE" IS 'pcseguidance';

COMMENT ON COLUMN "PMAPI_PRICE"."PM_PRICE" IS 'pcseguidance';

COMMENT ON COLUMN "PMAPI_PRICE"."MT20ID" IS 'mt20id';

ALTER TABLE "PMAPI" ADD CONSTRAINT "PK_PMAPI" PRIMARY KEY (
	"MT20ID"
);

ALTER TABLE "PMAPI_IMG" ADD CONSTRAINT "PK_PMAPI_IMG" PRIMARY KEY (
	"PMIMG_NO"
);

ALTER TABLE "PMAPI_PRICE" ADD CONSTRAINT "PK_PMAPI_PRICE" PRIMARY KEY (
	"PMPRICE_NO"
);

ALTER TABLE "PMAPI_IMG" ADD CONSTRAINT "FK_PMAPI_TO_PMAPI_IMG_1" FOREIGN KEY (
	"MT20ID"
)
REFERENCES "PMAPI" (
	"MT20ID"
);

ALTER TABLE "PMAPI_PRICE" ADD CONSTRAINT "FK_PMAPI_TO_PMAPI_PRICE_1" FOREIGN KEY (
	"MT20ID"
)
REFERENCES "PMAPI" (
	"MT20ID"
);
CREATE SEQUENCE SEQ_PMIMG_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PMPRICE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE "PM_GENRE" (
	"GENRE_NO"	NUMBER		NULL,
	"GENRE_NAME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PM_GENRE"."GENRE_NO" IS 'SEQ_PMGENRE_NO';

COMMENT ON COLUMN "PM_GENRE"."GENRE_NAME" IS 'genrenm';

ALTER TABLE "PM_GENRE" ADD CONSTRAINT "PK_PM_GENRE" PRIMARY KEY (
	"GENRE_NO"
);

CREATE SEQUENCE SEQ_ PMGENRE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE "PMAPI" DROP COLUMN "GENRE_NAME";

ALTER TABLE "PMAPI" ADD CONSTRAINT "FK_GENRE_TO_PMAPI_1" FOREIGN KEY ("GENRE_NO")
REFERENCES "PM_GENRE" ("GENRE_NO");

commit;
--------------------------------------------------------------------

INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '연극');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '뮤지컬');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '음악');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '무용');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '서커스/마술');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '복합');

commit;

INSERT INTO GENRE VALUES(1, '연극');
INSERT INTO GENRE VALUES(2, '뮤지컬');
INSERT INTO GENRE VALUES(3, '음악');
INSERT INTO GENRE VALUES(4, '무용');
INSERT INTO GENRE VALUES(5, '서커스/마술');
INSERT INTO GENRE VALUES(6, '복합');

commit;

-------------------------------------------------------------------------------------
INSERT INTO PMAPI(MT20ID)
VALUES('ZZZZZ');

SELECT * FROM PMAPI
WHERE MT20ID = 'ZZZZZ';

UPDATE PMAPI
SET
    BOARD_TITLE = '임시',
    B_CREATE_DATE = TO_DATE('2025.10.12 01:01:21', 'YYYY.MM.DD HH24:MI:SS'),
    PM_START_TIME = TO_DATE('1999.01.01', 'YYYY.MM.DD'),
    PM_END_TIME = TO_DATE('2000.01.01', 'YYYY.MM.DD'),
    PM_PLAYTIME = '대충20분',
    MT10ID = 'aaaaa',
    GENRE_NO = '1'
WHERE MT20ID = 'ZZZZZ';

ROLLBACK;

------------------------------------
-- 없는 목록 삭제
SELECT * FROM PMAPI_PRICE WHERE MT20ID = 'PF275784';


SELECT * FROM PMAPI
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

SELECT * FROM PMAPI_IMG
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

DELETE FROM PMAPI_IMG
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

DELETE FROM PMAPI
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

commit;

SELECT BOARD_NO, COUNT(*)
FROM BOARD_IMG
WHERE IMG_ORDER = 0
GROUP BY BOARD_NO
HAVING COUNT(*) > 1;


DELETE FROM BOARD_IMG
WHERE ROWID NOT IN (
  SELECT MIN(ROWID)
  FROM BOARD_IMG
  WHERE IMG_ORDER = 0
  GROUP BY BOARD_NO
);

ROLLBACK;


<<<<<<< HEAD

-------------
SELECT B.BOARD_NO, I.IMG_PATH AS POSTER
FROM BOARD B
JOIN BOARD_IMG I ON B.BOARD_NO = I.BOARD_NO
WHERE B.BOARD_DEL_FL = 'N' 
AND B.COMMUNITY_CODE = 4
AND I.IMG_ORDER = 0
ORDER BY B.B_CREATE_DATE DESC;
=======
--------------------------------------------------
-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO START WITH 10 NOCACHE;
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'user01@og.or.kr', 'pass01'
   , '유저일일', '0231532820', '06234,,서울특별시 마포구 월드컵북로 400 서울경제진흥원,,6층·8층', 'N',
   NULL, DEFAULT);
   
   commit;
   
   
   
-- 채팅방 시퀀스 번호 생성
CREATE SEQUENCE SEQ_CHATTING_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 메시지 번호 시퀀스
CREATE SEQUENCE SEQ_MESSAGE_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 게시판 종류 추가
INSERT INTO BOARDTYPE (COMMUNITY_CODE, COMMUNITY_NAME)
VALUES (1, '자유 게시판');

INSERT INTO BOARDTYPE (COMMUNITY_CODE, COMMUNITY_NAME)
VALUES (2, '리뷰 게시판');

INSERT INTO BOARDTYPE (COMMUNITY_CODE, COMMUNITY_NAME)
VALUES (3, '전시 게시판');

INSERT INTO BOARDTYPE (COMMUNITY_CODE, COMMUNITY_NAME)
VALUES (5, '문의 게시판');

COMMIT;

CREATE SEQUENCE SEQ_COMMENT_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_CONTRIBUTOR_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE SEQ_INSTITUTION_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

commit;

INSERT INTO QUESTION (Q_CODE, Q_NAME)
VALUES (1, '티켓');
COMMIT;
INSERT INTO QUESTION (Q_CODE, Q_NAME)
VALUES (2, '커뮤니티');
COMMIT;
INSERT INTO QUESTION (Q_CODE, Q_NAME)
VALUES (3, '회원/공통/기타');
COMMIT;
>>>>>>> 69742e5 (2025년 10월 15일  오후 06시 14분)
