INSERT INTO QUESTION (Q_CODE, Q_NAME)
VALUES (9, '안씀');

DROP TABLE "PMAPI";

CREATE TABLE "PMAPI" (
	"MT20ID"	VARCHAR2(100)		NULL,
	"BOARD_TITLE"	VARCHAR2(300)		NULL,
	"B_CREATE_DATE"	DATE		NULL,
	"GENRE_NO"	NUMBER		NULL,
	"GENRE_NAME"	VARCHAR2(50)		NULL,
	"PM_START_TIME"	DATE		NULL,
	"PM_END_TIME"	DATE		NULL,
	"PM_PLAYTIME"	VARCHAR2(500)		NULL,
	"MT10ID"	VARCHAR2(100)		NULL,
	"PM_HOUSE_NAME"	VARCHAR2(200)		NULL,
	"PM_HOUSE_ADDRESS"	VARCHAR2(500)		NULL,
	"PM_HOUSE_LAT"	BINARY_DOUBLE		NULL,
	"PM_HOUSE_LONG"	BINARY_DOUBLE		NULL,
	"PM_HOUSE_WEBSITE"	VARCHAR2(300)		NULL,
	"PM_HOUSE_HOME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PMAPI"."MT20ID" IS 'mt20id';

COMMENT ON COLUMN "PMAPI"."BOARD_TITLE" IS 'prfnm';

COMMENT ON COLUMN "PMAPI"."B_CREATE_DATE" IS 'updatedate';

COMMENT ON COLUMN "PMAPI"."GENRE_NO" IS 'SEQ_PMGENRE_NO';

COMMENT ON COLUMN "PMAPI"."PM_START_TIME" IS 'prfpdfrom';

COMMENT ON COLUMN "PMAPI"."PM_END_TIME" IS 'prfpdto';

COMMENT ON COLUMN "PMAPI"."PM_PLAYTIME" IS 'prfruntime';

COMMENT ON COLUMN "PMAPI"."MT10ID" IS 'mt10id';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_NAME" IS 'fcltynm';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_ADDRESS" IS 'adres';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_LAT" IS 'la';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_LONG" IS 'lo';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_WEBSITE" IS 'relateurl';

COMMENT ON COLUMN "PMAPI"."PM_HOUSE_HOME" IS 'telno';

DROP TABLE "PMAPI_IMG";

CREATE TABLE "PMAPI_IMG" (
	"PMIMG_NO"	NUMBER		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"IMG_PATH"	VARCHAR2(500)		NULL,
	"MT20ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PMAPI_IMG"."PMIMG_NO" IS 'SEQ_PMIMG_NO';

COMMENT ON COLUMN "PMAPI_IMG"."IMG_ORDER" IS 'poster=0, styurls=1~n';

COMMENT ON COLUMN "PMAPI_IMG"."IMG_PATH" IS 'poster, styurl';

COMMENT ON COLUMN "PMAPI_IMG"."MT20ID" IS 'mt20id';

DROP TABLE "PMAPI_PRICE";

CREATE TABLE "PMAPI_PRICE" (
	"PMPRICE_NO"	NUMBER		NOT NULL,
	"PM_PRICE_TYPE"	VARCHAR2(100)		NULL,
	"PM_PRICE"	NUMBER		NULL,
	"MT20ID"	VARCHAR2(100)		NULL
);

COMMENT ON COLUMN "PMAPI_PRICE"."PMPRICE_NO" IS 'SEQ_PMPRICE_NO';

COMMENT ON COLUMN "PMAPI_PRICE"."PM_PRICE_TYPE" IS 'pcseguidance';

COMMENT ON COLUMN "PMAPI_PRICE"."PM_PRICE" IS 'pcseguidance';

COMMENT ON COLUMN "PMAPI_PRICE"."MT20ID" IS 'mt20id';

ALTER TABLE "PMAPI" ADD CONSTRAINT "PK_PMAPI" PRIMARY KEY (
	"MT20ID"
);

ALTER TABLE "PMAPI_IMG" ADD CONSTRAINT "PK_PMAPI_IMG" PRIMARY KEY (
	"PMIMG_NO"
);

ALTER TABLE "PMAPI_PRICE" ADD CONSTRAINT "PK_PMAPI_PRICE" PRIMARY KEY (
	"PMPRICE_NO"
);

ALTER TABLE "PMAPI_IMG" ADD CONSTRAINT "FK_PMAPI_TO_PMAPI_IMG_1" FOREIGN KEY (
	"MT20ID"
)
REFERENCES "PMAPI" (
	"MT20ID"
);

ALTER TABLE "PMAPI_PRICE" ADD CONSTRAINT "FK_PMAPI_TO_PMAPI_PRICE_1" FOREIGN KEY (
	"MT20ID"
)
REFERENCES "PMAPI" (
	"MT20ID"
);
CREATE SEQUENCE SEQ_PMIMG_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PMPRICE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE "PM_GENRE" (
	"GENRE_NO"	NUMBER		NULL,
	"GENRE_NAME"	VARCHAR2(50)		NULL
);

COMMENT ON COLUMN "PM_GENRE"."GENRE_NO" IS 'SEQ_PMGENRE_NO';

COMMENT ON COLUMN "PM_GENRE"."GENRE_NAME" IS 'genrenm';

ALTER TABLE "PM_GENRE" ADD CONSTRAINT "PK_PM_GENRE" PRIMARY KEY (
	"GENRE_NO"
);

CREATE SEQUENCE SEQ_PMGENRE_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


ALTER TABLE "PMAPI" ADD CONSTRAINT "FK_GENRE_TO_PMAPI_1" FOREIGN KEY ("GENRE_NO")
REFERENCES "PM_GENRE" ("GENRE_NO");

commit;


INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '연극');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '뮤지컬');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '음악');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '무용');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '서커스/마술');
INSERT INTO PM_GENRE VALUES(SEQ_GENRE_NO.NEXTVAL, '복합');

DELETE FROM PMAPI_IMG
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

DELETE FROM PMAPI
WHERE MT20ID NOT IN (
    SELECT MT20ID
    FROM PMAPI_PRICE
    WHERE MT20ID IS NOT NULL
);

DELETE FROM PMAPI
WHERE MT20ID NOT IN (
    SELECT DISTINCT MT20ID
    FROM PMAPI_PRICE
    WHERE PM_PRICE IS NOT NULL
);


DELETE FROM PMAPI_IMG I
WHERE NOT EXISTS (
    SELECT 1 
    FROM PMAPI_PRICE P
    WHERE I.MT20ID = P.MT20ID
);


DELETE FROM PMAPI A
WHERE NOT EXISTS (
    SELECT 1 
    FROM PMAPI_PRICE B 
    WHERE A.MT20ID = B.MT20ID
);

commit;


SELECT 
    A.MT20ID,
    A.BOARD_TITLE AS 공연명
FROM PMAPI A
WHERE NOT EXISTS (
    SELECT 1 FROM PMAPI_PRICE B WHERE A.MT20ID = B.MT20ID
);



SELECT 
    A.MT20ID,
    A.BOARD_TITLE AS 공연명,
    COUNT(B.MT20ID) AS "가격 개수"
FROM PMAPI A
LEFT JOIN PMAPI_PRICE B
    ON A.MT20ID = B.MT20ID
GROUP BY A.MT20ID, A.BOARD_TITLE
ORDER BY "가격 개수" DESC;

SELECT 
    A.MT20ID,
    A.BOARD_TITLE AS 공연명
FROM PMAPI A
WHERE NOT EXISTS (
    SELECT 1 FROM PMAPI_PRICE B WHERE A.MT20ID = B.MT20ID
);

commit;
-------------------------------------------------------------------------------
-- 중복된 이미지 확인
SELECT 
    BOARD_NO,
    IMG_ORDER,
    COUNT(*) AS CNT
FROM BOARD_IMG
GROUP BY BOARD_NO, IMG_ORDER
HAVING COUNT(*) > 1
ORDER BY BOARD_NO, IMG_ORDER;

SELECT *
FROM BOARD_IMG I
WHERE (I.BOARD_NO, I.IMG_ORDER) IN (
    SELECT BOARD_NO, IMG_ORDER
    FROM BOARD_IMG
    GROUP BY BOARD_NO, IMG_ORDER
    HAVING COUNT(*) > 1
)
ORDER BY I.BOARD_NO, I.IMG_ORDER;

DELETE FROM BOARD_IMG
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM BOARD_IMG
    GROUP BY BOARD_NO, IMG_ORDER
);

commit;
DELETE FROM BOARD;

        INSERT INTO BOARD (
        	BOARD_NO, BOARD_TITLE, B_CREATE_DATE, BOARD_COUNT, BOARD_DEL_FL, COMMUNITY_CODE
        ) VALUES (
        	9899, '가나다라', TO_DATE( '2222.11.22 12:12:12' , 'YYYY.MM.DD HH24:MI:SS'), 0, 'N', 4
        );